# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /batman

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://database:5432/batman
      username: opengauss
      password: openGauss#2023
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  sql:
    init:
      mode: always
      schema-locations:
        - classpath*:sql/schema.sql
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  # quartz 调度器配置
  quartz:
    job-store-type: jdbc #数据持久化方式，可选值：MEMORY、JDBC
    auto-startup: true   #初始化后是否自动启动计划程序,默认为  true
    overwrite-existing-jobs: true #配置的作业是否应覆盖现有的作业定义
    scheduler-name: BatmanScheduler # 计划程序的名称
    startup-delay: 3s #初始化完成后启动计划程序的延迟时间，默认为 0 秒
    wait-for-jobs-to-complete-on-shutdown: false # 关闭时是否等待正在运行的作业完成
    properties:
      org:
        quartz:
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            tablePrefix: QRTZ_   #通知 JobStore 使用的表前缀
            misfireThreshold: 15000
            isClustered: true  #是否加入集群
            clusterCheckinInterval: 20000
            maxMisfiresToHandleAtATime: 1
            txIsolationLevelSerializable: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool  #quartz 使用的线程池类型，org.quartz.spi.ThreadPool
            threadCount: 20   #线程池中的线程总个数，表示最多可以同时执行的个任务/作业个数
            threadPriority: 5   #线程优先级
            threadsInheritContextClassLoaderOfInitializingThread: true #线程继承初始化线程的上下文类加载器
          scheduler:
              #quartz 调度器实例名称，相当于微服务架构中的微服务名称，instanceId 相当于微服务多实例时的节点 id
              #如果指定了 spring.quartz.scheduler-name 属性，则优先以它为准，此时 instanceName 不会生效.
            instanceName: BatmanScheduler
            instanceId: AUTO #实例id设置为自动获取，集群下的所有调度器实例id 必须为唯一.

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.opengauss.batman.modules.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

